name: 'cis9440_group8_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  cis9440_group8_project:
    group8_project:
      staging:
        +materialized: table
        +schema: cis9440_group8_staging

      marts:
        +materialized: table
        +schema: cis9440_group8_marts
