version: 2
sources:
  - name: raw
    description: Raw source tables for Group 8 project
    database: hrvojerubesa-cis9440-s26 #changed from natalia's az-dwh-class
    schema: cis9440_group8_dataset
    tables:
      - name: raw_311_requests
        identifier: raw_nyc_311_dot_and_nypd_data
        description: Raw 311 requests filtered to NYPD and DOT
        columns:
          - name: unique_key
          - name: created_date
          - name: closed_date
          - name: agency
          - name: agency_name
          - name: complaint_type
          - name: descriptor
          - name: descriptor_2
          - name: location_type
          - name: incident_zip
          - name: incident_address
          - name: street_name
          - name: cross_street_1
          - name: cross_street_2
          - name: intersection_street_1
          - name: intersection_street_2
          - name: address_type
          - name: city
          - name: landmark
          - name: facility_type
          - name: status
          - name: due_date
          - name: resolution_description
          - name: resolution_action_updated_date
          - name: community_board
          - name: council_district
          - name: police_precint
          - name: bbl
          - name: borough
          - name: x_coordinate_state_plane
          - name: y_coordinate_state_plane
          - name: latitude
          - name: longitude
          - name: tax_company_borough
          - name: tax_pickup_location
          - name: bridge_highway_name
          - name: bridge_highway_direction
          - name: road_ramp
          - name: bridge_highway_segment
          - name: open_data_channel_type
          - name: park_facility_name
          - name: park_borough
          - name: vehicle_type
      - name: raw_motor_vehicle_collisions
        identifier: source_motor_vehicle_collisions
        description: Raw motor vehicle collisions data
        columns:
          - name: borough
          - name: collision_id
          - name: contributing_factor_vehicle_1
          - name: contributing_factor_vehicle_2
          - name: contributing_factor_vehicle_3
          - name: contributing_factor_vehicle_4
          - name: contributing_factor_vehicle_5
          - name: crash_date
          - name: crash_time
          - name: cross_street_name
          - name: latitude
          - name: longitude
          - name: number_of_cyclist_injured
          - name: number_of_cyclist_killed
          - name: number_of_motorist_injured
          - name: number_of_motorist_killed
          - name: number_of_pedestrians_injured
          - name: number_of_pedestrians_killed
          - name: number_of_persons_injured
          - name: number_of_persons_killed
          - name: off_street_name
          - name: on_street_name
          - name: vehicle_type_code1
          - name: vehicle_type_code2
          - name: vehicle_type_code_3
          - name: vehicle_type_code_4
          - name: vehicle_type_code_5
          - name: zip_code
